In [5]:
import numpy as np
import random

In [24]:
m1 = np.matrix([[1, 2, 3], [1, 1, 0]])
m2 = np.matrix([[3, 8, 2], [2, 1, 7]])

In [25]:
np.inner(m1, m2)

matrix([[25, 25],
        [11,  3]])

In [21]:
m2

matrix([[ 3,  8,  2],
        [ 2,  1,  7],
        [13,  1,  9]])

In [18]:
m1 @ m2

matrix([[46, 13, 43],
        [ 5,  9,  9],
        [28,  3, 25]])

In [22]:
np.inner(m1, m2)

matrix([[25, 25, 42],
        [11,  3, 14],
        [12, 15, 19]])

## Random arrays

NameError: name 'random' is not defined

In [13]:

r1 = np.random.random((3, 3))
r2 = np.random.random((3,3))

r1+r2

array([[0.93505739, 1.15123131, 0.96732101],
       [1.04363283, 1.28766953, 0.19380204],
       [1.24487634, 0.74012583, 0.834357  ]])

In [1]:
import numpy as np

basis = {(0, 0):np.array([1, 0, 0, 0]), (1, 0):np.array([0, 0, 1, 0]),
        (0, 1):np.array([0, 1, 0, 0]), (1, 1):np.array([0, 0, 0, 1])}

AND = np.array([[1, 1, 1, 0], [0, 0, 0, 1]])
NOT = np.array([[0, 1], [1, 0]])
NAND = NOT @ AND
OR = np.array([[1, 0, 0, 0], [0, 1, 1, 1]])
def XOR(X): 
    or_neuron = np.matmul(OR, basis[X].T)
    nand_neuron = np.matmul(NAND, basis[X].T)
    l1_out = (or_neuron @ nand_neuron)
    return l1_out

In [5]:
XOR((0,1))

1